version: '3.1'

services:
  sql_server:
    container_name: sql_server
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    env_file:
      - .env
    ports:
      - "5500:1433"
    volumes:
      - db_mssql:/var/opt/mssql
volumes:
  db_mssql:
