version: '3.1'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_db
    restart: always
    env_file:
      - .env
    ports:
      - "1433:1433"
    volumes:
      - db_mssql:/var/opt/mssql
volumes:
  db_mssql:
